#ifndef FAULT_CODES_H
#define FAULT_CODES_H

#include <stdint.h>

typedef enum{
    FAULT_HEALTHY = 0x00,
    FAULT_PRESSURE1_SENSOR = 0x01,
    FAULT_TEMPERATURE1_SENSOR = 0x02,
    FAULT_TEMPERATURE2_SENSOR = 0x04,
    FAULT_TEMPERATURE3_SENSOR = 0x08,
    FAULT_COMP_OUTLET_TEMPERATURE_OVER = 0x10,
    FAULT_EVAP_INLET_TEMPERATURE_UNDER = 0x20,
    FAULT_COMP_INLET_LIQUID = 0x40,
    FAULT_COMP_INLET_PRESSURE_UNDER = 0x80,
    FAULT_ESTOP = 0x100,
} errorCode;

#endif